### PR TITLE
Backend Fiture

### PR DESCRIPTION
**Pull request by Junaidirah**
I've been working on the backend of Model and Migration features. 
this link for diagram DLOR 2024 [here](https://drawsql.app/teams/dlor-2024/diagrams/drec24)
this link for all off feature we have [here](https://docs.google.com/document/d/1IO5XPB400gPU8y8jMlAcco8eoUHeFmovDs4I4pHsmK0/edit)
Here are some lists that have been made.
**models**
- Datacaas
- Plotting
- Shift
- Status
- Grouprole

**migration**
- table datacaas
- table plotting
- table shift
- table statuses
- table group role

i made models with command from Laravel : php artisan make: model

### CODE REVIEW

**Comment by IritaSee** [comment]
Please edit the pull request title and add brief update~
[this blog](https://blog.crisp.se/2023/05/14/maxwenzin/how-to-do-great-pull-requests) can be a good reference to start!

**Comment by IritaSee** [comment]
These are quite long, hopefully we can check this ASAP, since it is going to take a bit more time. That is okay

and have you tested it locally? @Junaidirah

**Comment by Junaidirah** [comment]
> These are quite long, hopefully we can check this ASAP, since it is going to take a bit more time. That is okay
> 
> and have you tested it locally? @Junaidirah

Tried it, and so far, no issues have been encountered

**Review by fakhrip — APPROVED** [review]
Looks good to me, since these are just the database modelling part, everything is fine if it fits all the feature that you guys want to create 👍

**Comment by fakhrip** [comment]
Just a reminder to always create a PR as little as possible, such that its easier for us (the reviewer) to review it 👌

**Pull request merged**
